version: '3.8'

services:
  sql-server:
    build:
      context: ./database
      dockerfile: Dockerfile-sql
    container_name: ms-sql-server
    ports:
      - "1433:1433"

  dacpac-deployer:
    build:
      context: ./database
      dockerfile: Dockerfile
    depends_on:
      - sql-server

  web-api:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - dacpac-deployer
    ports:
      - "5000:5000"

