version: '3.8'

services:
  web-api:
    image: product-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "0000"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "Product"
      MSSQL_USER: "sa"
      MSSQL_PASSWORD: "0000"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - default

networks:
  default:
