# Use the official SQL Server 2019 image from Microsoft
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables for SQL Server
ENV SA_PASSWORD="0000"
ENV ACCEPT_EULA=Y
ENV MSSQL_DB="Product"

# Expose SQL Server port
EXPOSE 1433

# Start SQL Server on container startup
CMD ["/opt/mssql/bin/sqlservr"]
